language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:

script:
  - yarn run bootstrap
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - git stash
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && lerna publish --canary --yes --force-publish"
  skip_cleanup: true
  on:
    node: "10"
    tags: false